### ISSUE TITLE
Self-hosted Overleaf Sync Problem

### ISSUE THREAD

**Issue by Country-If** [subhamX/overleaf_sync_with_git#10]
I deployed an overleaf server using [overleaf/toolkit](https://github.com/overleaf/toolkit). I failed to sync after only adding the environment variable `OVERLEAF_HOST` and the corresponding secret. I found out my cookie name is `overleaf.sid`, not `overleaf_session2`. Therefore, I forked a new branch and updated the `Cookie` name in `src/entrypoint.sh`. In this way, I successfully synchronized.

What I want to say is that it is not that simple for a self-hosted overleaf to sync.

**Comment by subhamX** [comment]
An easy fix should be to change: https://github.com/subhamX/overleaf_sync_with_git/blob/master/src/entrypoint.sh#L24 to `"Cookie: overleaf_session2=$COOKIE;overleaf.sid=$COOKIE" \`. What do you think?

**Comment by Country-If** [comment]
It can help. However, I found that the `key` of the Cookie varies from different deployments, such as `overleaf_session2`, `overleaf.sid`, and `sharelatex.sid`. What I am trying to say is that there may be another different `key` of the Cookie. Thus, I think it would be more general to users set the `key` of their Cookies to `Secrets`.

**Comment by subhamX** [comment]
Oh, I didn't consider other platforms. 

I think your recommendation makes sense. So, let's by default set `overleaf_session2`, `overleaf.sid`, and `sharelatex.sid` (and anything else if you know). It doesn't hurt to do that. And the user can configure the key(s) themselves if they want.

**Comment by Country-If** [comment]
I think the default set with user-defined configuration approach is awesome.  However, I'm not sure how to modify the YAML file. I would appreciate it if the author could assist by making the necessary modifications.
