### ISSUE TITLE
有无不需要定期更新Secret的cookie的方案

### ISSUE THREAD

**Issue by Country-If** [subhamX/overleaf_sync_with_git#5]
cookie一般七天会过期，能否在Secret里保存Overleaf的账号密码，自动获取cookie，或者不使用cookie走账号密码

**Comment by subhamX** [comment]
That's strange. Last time I checked I found the cookie to be active for more than 2 months. Copying a small fragment of README (below), please have a look at it. If you're 100% sure that in 7 days your workflow isn't working, let me know, I'll spin the same test again to verify the results.

> IMPORTANT: I would recommend that after you copy overleaf_session2 cookie and put it in the GitHub actions secret, please delete the cookie from the browser. And then start a new browser session (by logging in again) if required. Please do not logout, it will make overleaf revoke the credentials. If you follow the above point, then the cookie should remain active for atleast 2 months, and the workflow should work without any issues. We've tested it in early 2023 by working a sample workflow for couple of months, and you can find the insights https://github.com/subhamX/overleaf_sync_with_git/pull/4#issuecomment-1355116634.

Finally to answer your question on programatically getting the token from email & password. It's tricky, cuz overleaf is protected by reCaptcha (from google). But will need to check if the API is protected by the login API or the site is using it just  for bots trying to scrape content, etc.

**Comment by Country-If** [comment]
Thank you for answering. I will try again and report issues when any arise.
